services:

  chatbot_fatec_whirlpool:
    # image: 'tarsislimafatec/chatbot_fatec_whirlpool'
    build: './src/chatbot_fatec_whirlpool'
    environment:
      - GEMINI_API_KEY=
    ports:
      - '80:5000'
      - '443:443'
